// teams.js

const teams = [
  {
    id: 0,
    teamName: 'Team A',
    wdl: { win: 3, draw: 1, lost: 1 },
    goalsScored: 7,
    goalsConceded: 3,
    red: 1,
    yellow: 0,
    location: 'Location 1',
  },
  {
    id: 1,
    teamName: 'Team B',
    wdl: { win: 4, draw: 2, lost: 2 },
    goalsScored: 3,
    goalsConceded: 3,
    red: 1,
    yellow: 2,
    location: 'Location 1',
  },
  {
    id: 2,
    teamName: 'Team C',
    wdl: { win: 3, draw: 1, lost: 1 },
    goalsScored: 2,
    goalsConceded: 3,
    red: 0,
    yellow: 5,
    location: 'Location 1',
  },
  {
    id: 3,
    teamName: 'Team D',
    wdl: { win: 1, draw: 4, lost: 3 },
    goalsScored: 1,
    goalsConceded: 1,
    red: 0,
    yellow: 0,
    location: 'Location 1',
  },
  {
    id: 4,
    teamName: 'Team E',
    wdl: { win: 1, draw: 4, lost: 3 },
    goalsScored: 1,
    goalsConceded: 1,
    red: 0,
    yellow: 0,
    location: 'Location 1',
  },
  {
    id: 5,
    teamName: 'Team F',
    wdl: { win: 2, draw: 3, lost: 3 },
    goalsScored: 2,
    goalsConceded: 4,
    red: 0,
    yellow: 2,
    location: 'Location 1',
  },
  {
    id: 6,
    teamName: 'Team G',
    wdl: { win: 3, draw: 2, lost: 2 },
    goalsScored: 4,
    goalsConceded: 2,
    red: 1,
    yellow: 1,
    location: 'Location 1',
  },
  {
    id: 7,
    teamName: 'Team H',
    wdl: { win: 2, draw: 2, lost: 3 },
    goalsScored: 3,
    goalsConceded: 4,
    red: 0,
    yellow: 3,
    location: 'Location 1',
  },
  // Additional members
  {
    id: 8,
    teamName: 'Team I',
    wdl: { win: 4, draw: 1, lost: 2 },
    goalsScored: 5,
    goalsConceded: 3,
    red: 2,
    yellow: 1,
    location: 'Location 2',
  },
  {
    id: 9,
    teamName: 'Team J',
    wdl: { win: 2, draw: 3, lost: 1 },
    goalsScored: 3,
    goalsConceded: 2,
    red: 0,
    yellow: 2,
    location: 'Location 2',
  },
  {
    id: 10,
    teamName: 'Team K',
    wdl: { win: 5, draw: 1, lost: 1 },
    goalsScored: 8,
    goalsConceded: 4,
    red: 1,
    yellow: 0,
    location: 'Location 2',
  },
  {
    id: 11,
    teamName: 'Team L',
    wdl: { win: 3, draw: 2, lost: 2 },
    goalsScored: 6,
    goalsConceded: 5,
    red: 1,
    yellow: 3,
    location: 'Location 2',
  },
  {
    id: 12,
    teamName: 'Team M',
    wdl: { win: 2, draw: 4, lost: 1 },
    goalsScored: 4,
    goalsConceded: 2,
    red: 0,
    yellow: 1,
    location: 'Location 2',
  },
  {
    id: 13,
    teamName: 'Team N',
    wdl: { win: 3, draw: 1, lost: 3 },
    goalsScored: 5,
    goalsConceded: 6,
    red: 2,
    yellow: 2,
    location: 'Location 2',
  },
  {
    id: 14,
    teamName: 'Team O',
    wdl: { win: 1, draw: 2, lost: 4 },
    goalsScored: 2,
    goalsConceded: 5,
    red: 0,
    yellow: 1,
    location: 'Location 2',
  },
  {
    id: 15,
    teamName: 'Team P',
    wdl: { win: 4, draw: 3, lost: 1 },
    goalsScored: 7,
    goalsConceded: 4,
    red: 1,
    yellow: 1,
    location: 'Location 2',
  },
];

export default teams;
